# Chapter 2 Lab - Intro to R

In [1]:
# creating a vector

x <- c(3, 1, 4, 1, 5, 9)
x

[1] 3 1 4 1 5 9

In [2]:
# get help on a command

?ls

ls                    package:base                     R Documentation

_L_i_s_t _O_b_j_e_c_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘ls’ and ‘objects’ return a vector of character strings giving the
     names of the objects in the specified environment.  When invoked
     with no argument at the top level prompt, ‘ls’ shows what data
     sets and functions a user has defined.  When invoked with no
     argument inside a function, ‘ls’ returns the names of the
     function's local variables: this is useful in conjunction with
     ‘browser’.

_U_s_a_g_e:

     ls(name, pos = -1L, envir = as.environment(pos),
        all.names = FALSE, pattern, sorted = TRUE)
     objects(name, pos= -1L, envir = as.environment(pos),
             all.names = FALSE, pattern, sorted = TRUE)
     
_A_r_g_u_m_e_n_t_s:

    name: which environment to use in listing the available objects.
          Defaults to the _current_ environment.  Although called
          ‘name’ for back compatibility, in fact this argument can
          specify the environment in any form; see the ‘Details’
          section.

     pos: an alternative argument to ‘name’ for specifying the
          environment as a position in the search list.  Mostly there
          for back compatibility.

   envir: an alternative argument to ‘name’ for specifying the
          environment.  Mostly there for back compatibility.

all.names: a logical value.  If ‘TRUE’, all object names are returned.
          If ‘FALSE’, names which begin with a ‘.’ are omitted.

 pattern: an optional regular expression.  Only names matching
          ‘pattern’ are returned.  ‘glob2rx’ can be used to convert
          wildcard patterns to regular expressions.

  sorted: logical indicating if the resulting ‘character’ should be
          sorted alphabetically.  Note that this is part of ‘ls()’ may
          take most of the time.

_D_e_t_a_i_l_s:

     The ‘name’ argument can specify the environment from which object
     names are taken in one of several forms: as an integer (the
     position in the ‘search’ list); as the character string name of an
     element in the search list; or as an explicit ‘environment’
     (including using ‘sys.frame’ to access the currently active
     function calls).  By default, the environment of the call to ‘ls’
     or ‘objects’ is used. The ‘pos’ and ‘envir’ arguments are an
     alternative way to specify an environment, but are primarily there
     for back compatibility.

     Note that the _order_ of strings for ‘sorted = TRUE’ is locale
     dependent, see ‘Sys.getlocale’.  If ‘sorted = FALSE’ the order is
     arbitrary, depending if the environment is hashed, the order of
     insertion of objects, ....

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘glob2rx’ for converting wildcard patterns to regular expressions.

     ‘ls.str’ for a long listing based on ‘str’.  ‘apropos’ (or ‘find’)
     for finding objects in the whole search path; ‘grep’ for more
     details on ‘regular expressions’; ‘class’, ‘methods’, etc., for
     object-oriented programming.

_E_x_a_m_p_l_e_s:

     .Ob <- 1
     ls(pattern = "O")
     ls(pattern= "O", all.names = TRUE)    # also shows ".[foo]"
     
     # shows an empty list because inside myfunc no variables are defined
     myfunc <- function() {ls()}
     myfunc()
     
     # define a local variable inside myfunc
     myfunc <- function() {y <- 1; ls()}
     myfunc()                # shows "y"

In [3]:
# check length of a vector

length(x)

[1] 6

In [4]:
# add 2 vectors

y <- c(2, 7, 1, 8, 2, 8)
y

ls() # list all objects (variables, functions, etc) in the environment

x + y

[1] 2 7 1 8 2 8

[1] "x" "y"

[1]  5  8  5  9  7 17

In [5]:
# remove/delete an object from the environment

ls()

rm(x)

ls()

[1] "x" "y"

[1] "y"

In [6]:
# remove all objects in the environment

ls()

rm(list = ls())

ls()

[1] "y"

character(0)

In [7]:
# create a matrix

set.seed(220526)
M <- matrix(sample(0:9, size = 4), nrow = 2, ncol = 2)
M

[,1] [,2]
[1,]    4    2
[2,]    9    1

In [8]:
# create a matrix by row instead of by column

U <- matrix(1:4, nrow = 2)
U

V <- matrix(1:4, nrow = 2, byrow = TRUE)
V

[,1] [,2]
[1,]    1    3
[2,]    2    4

[,1] [,2]
[1,]    1    2
[2,]    3    4

In [9]:
# elementwise operations on a matrix

U^2

sqrt(U)

[,1] [,2]
[1,]    1    9
[2,]    4   16

[,1]     [,2]
[1,] 1.000000 1.732051
[2,] 1.414214 2.000000

In [10]:
# generate vector of random normal variables

x <- rnorm(50) # defaults to mean 0 sd 1
y <- x + rnorm(50, mean = 50, sd = 0.1)

cor(x, y) # calculate correlation between x & y

[1] 0.9930664

In [11]:
?cor

cor                   package:stats                    R Documentation

_C_o_r_r_e_l_a_t_i_o_n, _V_a_r_i_a_n_c_e _a_n_d _C_o_v_a_r_i_a_n_c_e (_M_a_t_r_i_c_e_s)

_D_e_s_c_r_i_p_t_i_o_n:

     ‘var’, ‘cov’ and ‘cor’ compute the variance of ‘x’ and the
     covariance or correlation of ‘x’ and ‘y’ if these are vectors.  If
     ‘x’ and ‘y’ are matrices then the covariances (or correlations)
     between the columns of ‘x’ and the columns of ‘y’ are computed.

     ‘cov2cor’ scales a covariance matrix into the corresponding
     correlation matrix _efficiently_.

_U_s_a_g_e:

     var(x, y = NULL, na.rm = FALSE, use)
     
     cov(x, y = NULL, use = "everything",
         method = c("pearson", "kendall", "spearman"))
     
     cor(x, y = NULL, use = "everything",
         method = c("pearson", "kendall", "spearman"))
     
     cov2cor(V)
     
_A_r_g_u_m_e_n_t_s:

       x: a numeric vector, matrix or data frame.

       y: ‘NULL’ (default) or a vector, matrix or data frame with
          compatible dimensions to ‘x’.  The default is equivalent to
          ‘y = x’ (but more efficient).

   na.rm: logical. Should missing values be removed?

     use: an optional character string giving a method for computing
          covariances in the presence of missing values.  This must be
          (an abbreviation of) one of the strings ‘"everything"’,
          ‘"all.obs"’, ‘"complete.obs"’, ‘"na.or.complete"’, or
          ‘"pairwise.complete.obs"’.

  method: a character string indicating which correlation coefficient
          (or covariance) is to be computed.  One of ‘"pearson"’
          (default), ‘"kendall"’, or ‘"spearman"’: can be abbreviated.

       V: symmetric numeric matrix, usually positive definite such as a
          covariance matrix.

_D_e_t_a_i_l_s:

     For ‘cov’ and ‘cor’ one must _either_ give a matrix or data frame
     for ‘x’ _or_ give both ‘x’ and ‘y’.

     The inputs must be numeric (as determined by ‘is.numeric’: logical
     values are also allowed for historical compatibility): the
     ‘"kendall"’ and ‘"spearman"’ methods make sense for ordered inputs
     but ‘xtfrm’ can be used to find a suitable prior transformation to
     numbers.

     ‘var’ is just another interface to ‘cov’, where ‘na.rm’ is used to
     determine the default for ‘use’ when that is unspecified.  If
     ‘na.rm’ is ‘TRUE’ then the complete observations (rows) are used
     (‘use = "na.or.complete"’) to compute the variance.  Otherwise, by
     default ‘use = "everything"’.

     If ‘use’ is ‘"everything"’, ‘NA’s will propagate conceptually,
     i.e., a resulting value will be ‘NA’ whenever one of its
     contributing observations is ‘NA’.
     If ‘use’ is ‘"all.obs"’, then the presence of missing observations
     will produce an error.  If ‘use’ is ‘"complete.obs"’ then missing
     values are handled by casewise deletion (and if there are no
     complete cases, that gives an error).

     ‘"na.or.complete"’ is the same unless there are no complete cases,
     that gives ‘NA’.  Finally, if ‘use’ has the value
     ‘"pairwise.complete.obs"’ then the correlation or covariance
     between each pair of variables is computed using all complete
     pairs of observations on those variables.  This can result in
     covariance or correlation matrices which are not positive
     semi-definite, as well as ‘NA’ entries if there are no complete
     pairs for that pair of variables.  For ‘cov’ and ‘var’,
     ‘"pairwise.complete.obs"’ only works with the ‘"pearson"’ method.
     Note that (the equivalent of) ‘var(double(0), use = *)’ gives ‘NA’
     for ‘use = "everything"’ and ‘"na.or.complete"’, and gives an
     error in the other cases.

     The denominator n - 1 is used which gives an unbiased estimator of
     the (co)variance for i.i.d. observations.  These functions return
     ‘NA’ when there is only one observation (whereas S-PLUS has been
     returnin

In [12]:
# mean, variance and standard deviation of a vector

set.seed(3)

y <- rnorm(100)

mean(y)
var(y)
sqrt(var(y))
sd(y)

[1] 0.01103557

[1] 0.7328675

[1] 0.8560768

[1] 0.8560768