# 220313 Introduction to Python

## Python Basics

In [1]:
# comments start with hashtag #
# Python as a calculator

7 + 5

12

In [2]:
# print function (useful for debugging)

print(7/4)

1.75


In [3]:
# Python as a calculator
# If you don't use print function, only last calculation is printed

7 + 4
2/3

0.6666666666666666

In [4]:
# Python as a calculator

print(7+4)
print(2/3)
print(2*3)
print(2**3) # exponentiation
print(2%3) # modulo (remainder)

# See PEP8 Python style guide sections on spaces around operators https://peps.python.org/pep-0008/

11
0.6666666666666666
6
8
2


In [5]:
# what version of Python do I have?
# using import statement to gain access to Python modules/packages

import sys
print(sys.version)
print(sys.version_info)



3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)


In [6]:
# Variable assignment

x = 3
print(x)

3


In [7]:
# Calculations with variables

print(x*2)
print(x**2)
print(x%2)

6
9
1


In [8]:
# Variable types

x = 3
print(type(x)) # integer

y = 3.14
print(type(y)) # float

z = 'hello world'
print(type(z)) # string

w = False
print(type(w)) # boolean

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [9]:
# Same operation can behave differently on different variable types

print(x + x)
print(y + y)
print(z + z) # pastes/concatenates the two strings
print(w + w)

6
6.28
hello worldhello world
0


In [10]:
# To paste string and int/float, need to convert type

# z + x ## Error message: TypeError: must be str, not int

z + str(x) # converts type of x to str, see also int(), float(), bool()

'hello world3'

In [11]:
# convert string to float

w = '2.718'
print(2*w)
print(type(w))
print(2*float(w))

2.7182.718
<class 'str'>
5.436


## Python Lists

In [12]:
# Lists

x = 42
a = ['hello', x, 'hello world', 7, True, 2.718]
print(a)
type(a)

['hello', 42, 'hello world', 7, True, 2.718]


list

In [13]:
# List of lists

x = [['0th', 2], 
    ['1st', 1], 
    ['2nd', 7]]
print(x)
print(type(x))

[['0th', 2], ['1st', 1], ['2nd', 7]]
<class 'list'>


In [14]:
# Subsetting lists

x = [['1st', 2], 
    ['2nd', 1], 
    ['3rd', 7], 
    ['4th', 8]]
print(x)
print('')

print(x[1]) # Python uses zero-based array indexing
print('')

print(x[-1]) # negative indexing
print('')

[['1st', 2], ['2nd', 1], ['3rd', 7], ['4th', 8]]

['2nd', 1]

['4th', 8]



In [15]:
# Subsetting lists

print(x[0][1])
print(x[-1][1])
x[0][1] + x[-1][1]

2
8


10

In [16]:
# Subsetting lists: slicing

x = [2, 7, 1, 8]

print(x[0:2])

print(type(x[0:2]))

print(x[0:1])
print(type(x[0:1]))

print(x[0])
print(type(x[0]))

[2, 7]
<class 'list'>
[2]
<class 'list'>
2
<class 'int'>


In [17]:
# Subsetting lists: slicing

print(x)

print(x[:2]) # first two elements

print(x[-3:]) # last three elements

# See PEP8 Python style guide sections on spaces around operators https://peps.python.org/pep-0008/

[2, 7, 1, 8]
[2, 7]
[7, 1, 8]


In [18]:
# replace list elements

x = [2, 7, 1, 8]
print(x)
print('')

x[1] = 6 # replace 2nd element
print(x)
print('')

x[-2:] = [3, 9] # replace the last 2 elements
print(x)
print('')

[2, 7, 1, 8]

[2, 6, 1, 8]

[2, 6, 3, 9]



In [19]:
# extend (add elements to) a list

x = [2, 7, 1, 8]
print(x)
print('')

x + [2, 8]

[2, 7, 1, 8]



[2, 7, 1, 8, 2, 8]

In [20]:
# access previous output/result of last evaluation

1 + 2

3

In [21]:
# access previous output/result of last evaluation

4 + _

7

In [22]:
# access previous output/result of last evaluation

8 + _20 # in a jupyter shell you can also access previous outputs by their number e.g. [20] would be _20

11

In [23]:
# delete list elements

x = [2, 7, 1, 8]
print(x)
print('')

del(x[1])
print(x)
print('')

del(x[-1])
print(x)
print('')

[2, 7, 1, 8]

[2, 1, 8]

[2, 1]



In [24]:
# copying lists (shallow vs deep?)

x = [2, 7, 1, 8]
print(x)
print('')

x_copy = x
print(x_copy)
print('')

del(x_copy[-1])
print(x_copy)
print('')

print(x)
print('')

# changing x_copy also changes x

[2, 7, 1, 8]

[2, 7, 1, 8]

[2, 7, 1]

[2, 7, 1]



In [25]:
# copying lists (shallow vs deep?)

x = [2, 7, 1, 8]
print(x)
print('')

x_copy = x[:] # copy using slicing
print(x_copy)
print('')

del(x_copy[-1])
print(x_copy)
print('')

print(x)
print('')

# changing x_copy does NOT change x

[2, 7, 1, 8]

[2, 7, 1, 8]

[2, 7, 1]

[2, 7, 1, 8]



In [26]:
# https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-3-functions-and-packages?ex=1
# https://stackoverflow.com/questions/4794244/how-can-i-create-a-copy-of-an-object-in-python

## Functions and Packages

In [27]:
# Functions

x = [2, 7, 1, 8]
print(x, '\n')

print(max(x), '\n')

[2, 7, 1, 8] 

8 



In [28]:
# Functions

x = 2.718
print(x, '\n')

print(round(x, 2), '\n')

print(round(x), '\n')

2.718 

2.72 

3 



In [29]:
# Get help on a function

help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [30]:
# function round with negative ndigits

x = 2.718
print(x, '\n')

print(round(x, -1), '\n')

2.718 

0.0 



In [31]:
# get length of a list

x = [2, 7, 1, 8]
print(x, '\n')

len(x)

[2, 7, 1, 8] 



4

In [32]:
# sort a list

help(sorted)

x = [2, 7, 1, 8]
print(x, '\n')

print(sorted(x), '\n') # default is ascending

print(sorted(x, reverse=True), '\n') # sort descending

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[2, 7, 1, 8] 

[1, 2, 7, 8] 

[8, 7, 2, 1] 



In [33]:
# methods aka functions that belong to objects

x = [2, 7, 1, 8, 2, 8]
print(x, '\n')

print(x.index(2), '\n') # returns first index of 2

print(x.count(2), '\n')

[2, 7, 1, 8, 2, 8] 

0 

2 



In [34]:
# string methods

x = 'hello world'
print(x, '\n')

print(x.capitalize(), '\n')

z = x.replace('world', 'mundo')

print(x) # the capitalize & replace didn't change x
print(z) # the replace applied to z but not x

hello world 

Hello world 

hello world
hello mundo


In [35]:
# list methods

x = [2, 7, 1, 8, 2, 8]
print(x, '\n')

x.append(1) # method changes the original list x
print(x, '\n')

[2, 7, 1, 8, 2, 8] 

[2, 7, 1, 8, 2, 8, 1] 



In [36]:
# what are the methods for strings?

help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [37]:
# string methods

x = 'hello world'
print(x, '\n')

y = x.upper() # to all caps (uppercase)
print(y)
print(x, '\n') # x was not changed

x.count('o') # count occurences of 'o'

hello world 

HELLO WORLD
hello world 



2

In [38]:
# list methods

x = [2, 7, 1, 8, 2, 8]
print(x, '\n')

print(x.index(8), '\n') # returns first location of '8'

x.count(2) # how many times does '2' appear in list x?

[2, 7, 1, 8, 2, 8] 

3 



2

In [39]:
# list methods

x = [2, 7, 1, 8, 2, 8]
print(x, '\n')

x.append(1) # add 1 to the end of x
print(x, '\n') # x is changed

x.remove(2) # removes first 2 in x
print(x, '\n') # x is changed

x.reverse() # reverses x
print(x) # x is changed

[2, 7, 1, 8, 2, 8] 

[2, 7, 1, 8, 2, 8, 1] 

[7, 1, 8, 2, 8, 1] 

[1, 8, 2, 8, 1, 7]


In [40]:
# what are the list methods?

help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [41]:
# python packages

import math # import package

help(math)

print(math.pi)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in 

In [42]:
# import specific module from package

from math import pi # selective import

print('pi to 15 decimal places is: ' + str(pi)) # str converts type of pi from float to str allowing concatenation

pi to 15 decimal places is: 3.141592653589793


## Numpy

In [43]:
# numpy

import numpy as np

np.__version__ # check version of Python package

'1.21.5'

In [44]:
# creating a numpy array from a list

import numpy as np

x = [2, 7, 1, 8, 2]
print(x)
print(type(x), '\n')

y = np.array(x)
print(y)
print(type(y), '\n')

[2, 7, 1, 8, 2]
<class 'list'> 

[2 7 1 8 2]
<class 'numpy.ndarray'> 



In [45]:
# element-wise operation on numpy array

import numpy as np
import math

x = [3, 1, 4, 1, 5, 9]
x = np.array(x)
print(x, '\n')

print(math.e * x) # would give error if x were a list

[3 1 4 1 5 9] 

[ 8.15484549  2.71828183 10.87312731  2.71828183 13.59140914 24.46453646]


In [46]:
# element-wise operation on numpy array

import numpy as np
import math

x = np.array([3, 1, 4, 1, 5, 9])
y = np.array([2, 7, 1, 8, 2, 8])

print(x, '\n')

print(y, '\n')

print('x divided by y is: ' + str(x/y)) # would not work if x & y were lists

[3 1 4 1 5 9] 

[2 7 1 8 2 8] 

x divided by y is: [1.5        0.14285714 4.         0.125      2.5        1.125     ]


In [47]:
# subsetting numpy arrays

import numpy as np

x = np.array([3, 1, 4, 1, 5, 9])
print(x, '\n')

print(x[2], '\n') # subsetting using square brackets

print(x > 3, '\n') # boolean array

print(x[x > 3]) # subsetting using boolean array

[3 1 4 1 5 9] 

4 

[False False  True False  True  True] 

[4 5 9]


In [48]:
# unlike lists, np.array only contain one type i.e. all str, or all float, or all boolean, etc
# if you give np.array list containing heterogeneous elements, will try & force all to be one type (type coercion)

import numpy as np

y = [2, 7, '1', 8, 2]
print(y, '\n')

print(np.array(y), '\n') # converts all to str

x = [3, 1, [4, 1], 5, 9]
print(x, '\n')

print(np.array(x))

[2, 7, '1', 8, 2] 

['2' '7' '1' '8' '2'] 

[3, 1, [4, 1], 5, 9] 

[3 1 list([4, 1]) 5 9]


/var/folders/gw/0wg9zm9d27s9dhd46rrzb4_c0000gp/T/ipykernel_60598/878570334.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(x))


In [49]:
# arithmetic operators + - * / work differently on np.array vs list

import numpy as np

x = [3, 1, 4]
y = [2, 7, 1]

print(x + y, '\n') # concatenates

print(np.array(x) + np.array(y)) # adds element-wise

[3, 1, 4, 2, 7, 1] 

[5 8 5]


In [50]:
# 2D numpy array

# creating 2D numpy array from list of lists

import numpy as np

x = [3, 1, 4]
y = [2, 7, 1]
z = [x, y]

print(z, '\n') # list of lists

print(np.array(z), type(np.array(z)), '\n') # np.ndarray

print(np.array(z).shape, '\n') # dimensions/shape of array

print(np.array(y).shape) # default is to make column vector from 1D object (elements are rows)

[[3, 1, 4], [2, 7, 1]] 

[[3 1 4]
 [2 7 1]] <class 'numpy.ndarray'> 

(2, 3) 

(3,)


In [51]:
# subsetting 2d numpy arrays

import numpy as np

x = [3, 1, 4, 1, 5, 9]
y = [2, 7, 1, 8, 2, 8]

z = np.array([x, y])
print(z, '\n')
print(z.shape, '\n')

print(z[:, 1:3], '\n') # slicing - all rows

print(z[1, :], '\n') # slicing - all columns

print(z[1]) # this also works to select all columns!

[[3 1 4 1 5 9]
 [2 7 1 8 2 8]] 

(2, 6) 

[[1 4]
 [7 1]] 

[2 7 1 8 2 8] 

[2 7 1 8 2 8]


In [52]:
# 2d arithmetic

import numpy as np

x = [3, 1, 4, 1, 5, 9]
y = [2, 7, 1, 8, 2, 8]

z = np.array([x, y])
print(z, '\n')
print(z.shape, '\n') # 2 rows & 6 columns

print(z * 2, '\n') # element-wise scalar multiplication

print(z ** 2, '\n') # element-wise exponentiation NOT matrix multiplication!

print(z + 1, '\n') # element-wise scalar addition

print(z + np.array([[2], [3]]), '\n') # add column vector [[2],[3]] to every column of z

print(z + np.array([1, 2, 3, 4, 5, 6]), '\n') # add row vector [1, 2, 3, 4, 5, 6] to every row of z

print(z.shape) # 2 x 6
print(np.array([1, 2, 3, 4, 5, 6]).shape) # 6 x 1
print(z * np.array([1, 2, 3, 4, 5, 6]), '\n') # NOT matrix-vector multiplication!! 
                                                # that's why final result is 2 x 6 NOT 2 x 1

print(z + 2*z) # matrix addition

[[3 1 4 1 5 9]
 [2 7 1 8 2 8]] 

(2, 6) 

[[ 6  2  8  2 10 18]
 [ 4 14  2 16  4 16]] 

[[ 9  1 16  1 25 81]
 [ 4 49  1 64  4 64]] 

[[ 4  2  5  2  6 10]
 [ 3  8  2  9  3  9]] 

[[ 5  3  6  3  7 11]
 [ 5 10  4 11  5 11]] 

[[ 4  3  7  5 10 15]
 [ 3  9  4 12  7 14]] 

(2, 6)
(6,)
[[ 3  2 12  4 25 54]
 [ 2 14  3 32 10 48]] 

[[ 9  3 12  3 15 27]
 [ 6 21  3 24  6 24]]


In [53]:
# numpy basic statistics: mean, median, stdev, correlation

import numpy as np

x = [3, 1, 4, 1, 5, 9]
y = [2, 7, 1, 8, 2, 8]

z = np.array([x, y])
print(z)
print(z.shape, '\n') # 2 rows & 6 columns

z_mean_c2 = np.mean(z[:, 1]) # mean of second column
print(z_mean_c2, '\n')

z_median_r2 = np.median(z[1, :]) # median of second row
print(z_median_r2, '\n')

z_stddev_r1 = np.std(z[0, :]) # standard deviation of first row
print('std dev row 1: ' + str(z_stddev_r1), '\n')

z_corr_r1r2 = np.corrcoef(z[0, :], z[1, :]) # correlation between first and second row
print('correlation between two rows of z is: ' + str(z_corr_r1r2))

[[3 1 4 1 5 9]
 [2 7 1 8 2 8]]
(2, 6) 

4.0 

4.5 

std dev row 1: 2.733536577809454 

correlation between two rows of z is: [[ 1.         -0.00669245]
 [-0.00669245  1.        ]]


In [54]:
# numpy basic stats

x = ["C", "C", "T", "C", "A", "G", "G", "C", "C", "C"]
y = [2, 7, 1, 8, 2, 8, 1, 8, 2, 8]

x = np.array(x)
y = np.array(y)

print(x)
print(y, '\n')

print(y[x == 'C'])
print(y[x != 'C'], '\n') # subset y using x

print(np.median(y[x == 'C']))
print(np.median(y[x != 'C']))

['C' 'C' 'T' 'C' 'A' 'G' 'G' 'C' 'C' 'C']
[2 7 1 8 2 8 1 8 2 8] 

[2 7 8 8 2 8]
[1 2 8 1] 

7.5
1.5
