# 220313 Introduction to R

In [1]:
# comments start with hashtag #
# R as a calculator

7 + 4

[1] 11

In [2]:
# R as a calculator

7 + 4
8 - 2

2^10 # exponentiation
2 %% 3 # modulo/remainder

# see tidyverse style guide about spaces https://style.tidyverse.org/index.html 
# "Most infix operators (==, +, -, <-, etc.) should always be surrounded by spaces"
# "The operators with high precedence: ::, :::, $, @, [, [[, ^, unary -, unary +, and : should never be surrounded by spaces"

[1] 11

[1] 6

[1] 1024

[1] 2

In [3]:
# Assigning variables

x <- 3.14
x
y <- 2
y
x^y
z <- x - y
z

[1] 3.14

[1] 2

[1] 9.8596

[1] 1.14

In [4]:
# Basic data types in R

x <- 2 # numeric (integer)
class(x)

y <- FALSE # boolean/logical
class(y)

z <- 'hello world' # character/string
class(z)

[1] "numeric"

[1] "logical"

[1] "character"

In [5]:
# Vectors in R

x <- c(3, 1, 4, 1, 5)
y <- c('hello', 'world')
z <- c(FALSE, TRUE, FALSE)
x
y
z

[1] 3 1 4 1 5

[1] "hello" "world"

[1] FALSE  TRUE FALSE

In [6]:
# Naming elements of vectors
names(x)
names(x) <- c('1st', '2nd', '3rd', '4th', '5th')
x
names(x)

NULL

1st 2nd 3rd 4th 5th 
  3   1   4   1   5

[1] "1st" "2nd" "3rd" "4th" "5th"

In [7]:
# Naming elements of vectors

names(z)
people <- c('Ava', 'Betty', 'Christie')
names(z) <- people
z
names(z)

NULL

Ava    Betty Christie 
   FALSE     TRUE    FALSE

[1] "Ava"      "Betty"    "Christie"

In [8]:
# Operations with vectors

x1 <- c(3, 1, 4)
x2 <- c(2, 7, 1)
x1
x2
x1 + x2
x1 / x2
x1 > x2

# element-by-element

[1] 3 1 4

[1] 2 7 1

[1] 5 8 5

[1] 1.5000000 0.1428571 4.0000000

[1]  TRUE FALSE  TRUE

In [9]:
# Operations with vectors
x1
sum(x1)
x2
sum(x2)

[1] 3 1 4

[1] 8

[1] 2 7 1

[1] 10

In [10]:
# Vector element selection
# R unlike Python uses 1-based array indexing (Python uses 0-based array indexing)

x1
x1[0] # no 0th element 0
x1[1]
x1[-2] # drops 2nd element

[1] 3 1 4

numeric(0)

[1] 3

[1] 3 4

In [11]:
# Vector element selection: multiple elements

x <- c(2, 7, 1, 8, 2, 8, 1, 8, 2, 8)
#print(exp(1)*1e9)
print(x)

x[2:4] # select consecutive elements

x[-c(2:4)] # drop consecutive elements

x[c(3, 1, 4)] # select non-consecutive elements

 [1] 2 7 1 8 2 8 1 8 2 8


[1] 7 1 8

[1] 2 2 8 1 8 2 8

[1] 1 2 8

In [12]:
# Vector element selection: using names of elements

#print(pi*1e9)

y <- c(3, 1, 4, 1, 5, 9, 2, 6, 5, 4)
set.seed(24)
names(y) <- sample(LETTERS, 10)

y

y['J']

y[c('I', 'G', 'W')]

mean(.Last.value)

y[c('B', 'X')]
y['B'] + y['X']

G S H W B C J I Y X 
3 1 4 1 5 9 2 6 5 4

J 
2

I G W 
6 3 1

[1] 3.333333

B X 
5 4

B 
9

In [13]:
# Vector element selection: by comparison i.e. using logical comparison operators > < >= <= == !=

u <- c(2, 7, 1, 8, 2, 8, 1, 8, 2, 8)

u > 2

u[u > 2]

[1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

[1] 7 8 8 8 8

In [14]:
# Creating matrix

M <- matrix(1:9, byrow = TRUE, nrow = 3)
M

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [15]:
# Naming matrix dimensions

rownames(M) <- c('r1', 'r2', 'r3')
colnames(M) <- c('c1', 'c2', 'c3')
M

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

In [16]:
# Summing rows & columns of matrix

M
rowSums(M)
colSums(M)

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

r1 r2 r3 
 6 15 24

c1 c2 c3 
12 15 18

In [17]:
# Adding rows & columns to matrix

M
rbind(M, c(10, 11, 12)) # add row
cbind(M, c(10, 11, 12)) # add column

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9
   10 11 12

c1 c2 c3   
r1 1  2  3  10
r2 4  5  6  11
r3 7  8  9  12

In [18]:
# What objects do I have in my environment?

ls()

[1] "M"      "people" "u"      "x"      "x1"     "x2"     "y"      "z"

In [19]:
# Selecting matrix elements

M
M[1, 2]
M[2, 3]
M[1:2, 2:3]
M[, 2] # all elements of column 2
M[3, ] # all elements of row 3

# see tidyverse style guide about spaces https://style.tidyverse.org/index.html 
# 'Always put a space after a comma, never before, just like in regular English.'

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

[1] 2

[1] 6

c2 c3
r1 2  3 
r2 5  6

r1 r2 r3 
 2  5  8

c1 c2 c3 
 7  8  9

In [20]:
# summary stats of matrix

M
mean(M)
median(M)
sd(M) # standard deviation
max(M)
min(M)

summary(M)
summary(t(M))

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

[1] 5

[1] 5

[1] 2.738613

[1] 9

[1] 1

       c1            c2            c3     
 Min.   :1.0   Min.   :2.0   Min.   :3.0  
 1st Qu.:2.5   1st Qu.:3.5   1st Qu.:4.5  
 Median :4.0   Median :5.0   Median :6.0  
 Mean   :4.0   Mean   :5.0   Mean   :6.0  
 3rd Qu.:5.5   3rd Qu.:6.5   3rd Qu.:7.5  
 Max.   :7.0   Max.   :8.0   Max.   :9.0  

       r1            r2            r3     
 Min.   :1.0   Min.   :4.0   Min.   :7.0  
 1st Qu.:1.5   1st Qu.:4.5   1st Qu.:7.5  
 Median :2.0   Median :5.0   Median :8.0  
 Mean   :2.0   Mean   :5.0   Mean   :8.0  
 3rd Qu.:2.5   3rd Qu.:5.5   3rd Qu.:8.5  
 Max.   :3.0   Max.   :6.0   Max.   :9.0  

In [21]:
# Element-wise matrix arithmetic

M
M^2 # squares each element
M%%2 # checks if each element is odd/even

M/3
M - 1
log(M)

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

c1 c2 c3
r1  1  4  9
r2 16 25 36
r3 49 64 81

c1 c2 c3
r1 1  0  1 
r2 0  1  0 
r3 1  0  1

c1        c2        c3
r1 0.3333333 0.6666667 1 
r2 1.3333333 1.6666667 2 
r3 2.3333333 2.6666667 3

c1 c2 c3
r1 0  1  2 
r2 3  4  5 
r3 6  7  8

c1       c2        c3      
r1 0.000000 0.6931472 1.098612
r2 1.386294 1.6094379 1.791759
r3 1.945910 2.0794415 2.197225

In [22]:
# Element-wise vs standard matrix multiplication

set.seed(51)
N <- matrix(sample(0:9, size = 9, replace = TRUE), nrow = 3)
N
M

M*N # Element-wise
N*M # Element-wise

# for Element-wise, order makes no difference

M%*%N # standard
N%*%M # standard

# for standard, order DOES make a difference

[,1] [,2] [,3]
[1,] 6    0    7   
[2,] 2    4    9   
[3,] 7    1    5

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

c1 c2 c3
r1  6  0 21
r2  8 20 54
r3 49  8 45

c1 c2 c3
r1  6  0 21
r2  8 20 54
r3 49  8 45

[,1] [,2] [,3]
r1  31  11    40 
r2  76  26   103 
r3 121  41   166

c1 c2 c3 
[1,] 55 68  81
[2,] 81 96 111
[3,] 46 59  72

In [23]:
# Factors (used to store categorical variables)

set.seed(91)
eye_color <- sample(c('black', 'brown', 'blue', 'green'), size = 10, replace = TRUE)
eye_color
class(eye_color)

# change from 'character' to 'factor'

eye_color_factor <- factor(eye_color)
eye_color_factor
class(eye_color_factor)

[1] "black" "green" "blue"  "brown" "green" "green" "blue"  "blue"  "black"
[10] "brown"

[1] "character"

[1] black green blue  brown green green blue  blue  black brown
Levels: black blue brown green

[1] "factor"

In [24]:
# Factors; nominal vs ordinal categorical variables

eye_color_factor # nominal (no order in the levels of color)
levels(eye_color_factor)

set.seed(74)
temperature <- sample(c('Medium', 'Low', 'High'), size = 10, replace = TRUE)
temperature
class(temperature)

temperature_factor <- factor(temperature, order = TRUE, levels = c('Low', 'Medium', 'High'))
temperature_factor
levels(temperature_factor)

[1] black green blue  brown green green blue  blue  black brown
Levels: black blue brown green

[1] "black" "blue"  "brown" "green"

[1] "Low"  "Low"  "High" "Low"  "Low"  "High" "High" "Low"  "High" "Low"

[1] "character"

[1] Low  Low  High Low  Low  High High Low  High Low 
Levels: Low < Medium < High

[1] "Low"    "Medium" "High"

In [25]:
# change names of levels of a factor

set.seed(14)
x <- sample(c('R', 'B'), size = 10, replace = TRUE)
x_factor <- factor(x)
x_factor
levels(x_factor)

levels(x_factor) <- c('Blue', 'Red')
x_factor

[1] R R R B R B B B B B
Levels: B R

[1] "B" "R"

[1] Red  Red  Red  Blue Red  Blue Blue Blue Blue Blue
Levels: Blue Red

In [27]:
R.Version()

$platform
[1] "x86_64-apple-darwin13.4.0"

$arch
[1] "x86_64"

$os
[1] "darwin13.4.0"

$system
[1] "x86_64, darwin13.4.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "6.1"

$year
[1] "2019"

$month
[1] "07"

$day
[1] "05"

$`svn rev`
[1] "76782"

$language
[1] "R"

$version.string
[1] "R version 3.6.1 (2019-07-05)"

$nickname
[1] "Action of the Toes"